services:
api:
    build: .
    image: ryan_website_api:prod
    ports:
    - "127.0.0.1:8000:8000"
    env_file:
    - .env.prod
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
